### ISSUE TITLE
Do not disallow morphing a Task into an Expanded subprocess

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/bpmn-js-disable-collapsed-subprocess#31]
__Describe the Bug__

Currently this module disables the morphing of a `Task` into an `Expanded Subprocess`. This isn't behavior that we particularly want though as expanded subprocesses are supported in platform 8 and this morphing behavior is present in platform 7

__Steps to Reproduce__

1. Create a C8 bpmn diagram in the modeler (where this module is used)
2. Try to morph a Task into an Expanded Subprocess
3. Option is not available

__Expected Behavior__

The option should be available.

**Comment by MaxTru** [comment]
Makes sense. As stated in #30 and to make it even clearer:

** A callActivity may be morphed to expanded/collapsed subprocess**
![Screenshot_20220413_120536](https://user-images.githubusercontent.com/42800119/163155097-c463e356-448d-4b94-a651-6a929bc4403a.png)

**Tasks may only be morphed to a collapsed subprocess**
![Screenshot_20220413_120644](https://user-images.githubusercontent.com/42800119/163155297-4fa9a0a7-0aea-4f89-a53c-d16ee9d59d9e.png)


We should be consistent. Morphing to collapsed or expanded subprocesses is fine, as long as the option to make an expanded subprocess a collapsed one, is not shown.
